copyright: 2020 Jacob Torrång
maintainer: kopatheonlyone@hotmail.com

name: game
version: 0.1.0.0
extra-source-files:
  - README.md
author: mewhhaha
github: mewhhaha/apecs-unity-tutorial-haskell
license: null

dependencies:
  - base >= 4.7 && < 5
  - polysemy
  - polysemy-plugin
  - sdl2
  - sdl2-image
  - sdl2-mixer
  - sdl2-ttf
  - apecs
  - linear
  - containers
  - random
  - mtl
  - array
  - filepath
  - rapid
  - bytestring
  - typelits-witnesses
  - text
  - StateVar

ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  - -O2
  - -fplugin=Polysemy.Plugin
  - -Wall

library:
  source-dirs: src

executables:
  game-exe:
    source-dirs: app
    main: Main.hs
    dependencies:
      - game

description: Please see the README on GitHub at <https://github.com/mewhhaha/apecs-unity-tutorial-haskell#readme>
